src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ad", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\GreaterThan("today", message="La date d'arrivée doit être ultérieure à la date d'aujourd'hui !", groups={"front"})
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\GreaterThan(propertyPath="startDate", message="La date de départ doit être plus éloignée que la date d'arrivée.")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * @ORM\Column(type="boolean")
     */
    private $payment=false;

    /**
     * Callback appelé à chaque fois que l'on crée une réservation
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * @return void
     */
    public function prePersist()
    {
        if (empty($this->createdAt)) {

            $this->createdAt = new \DateTime();
        }

        if (empty($this->amount)) {

            // Prix de l'annonce * nombre de jour
            $this->amount = $this->ad->getPrice() * $this->getDuration();
        }
    }

    public function isBookableDates()
    {
        // 1. Connaitre les dates impossibles pour l'annonce
        $notAvailableDays = $this->ad->getNotAvailableDays();
        // 2. Comparer les dates choisi avec les dates impossibles
        $bookingDays = $this->getDays();

        // Petite fonction anonym
        $formatDay = function ($day) {
            return $day->format('Y-m-d');
        };
        // Tableau de chaine de caractères de mes journées
        $days = array_map($formatDay, $bookingDays);

        $notAvailable = array_map($formatDay, $notAvailableDays);

        foreach ($days as $day) {
            if (array_search($day, $notAvailable) !== false) return false;
        }

        return true;
    }

    /**
     * Permet de récupérer un taleau des journées qui correspondent à ma  réservation 
     *
     * @return array Un tableau d'objets DateTime représentant les jours de la réservation
     */
    public function getDays()
    {
        $resultat = range(
            $this->getStartDate()->getTimestamp(),
            $this->getEndDate()->getTimestamp(),
            24 * 60 * 60
        );

        $days = array_map(function ($dayTimestamp) {
            return new \DateTime(date('Y-m-d', $dayTimestamp));
        }, $resultat);

        return $days;
    }
    public function getDuration()
    {
        $diff = $this->endDate->diff($this->startDate);

        return $diff->days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getPayment(): ?bool
    {
        return $this->payment;
    }

    public function setPayment(bool $payment): self
    {
        $this->payment = $payment;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 * fields={"email"},
 * message="Un autre utilisateur s'est déjà inscrit avec cette adresse mail, merci de la modifier !"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseigner votre prénom")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseigner votre nom de famille")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Veuillez renseignez un email valid")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url(message="Veuillez renseigner une adresse mail valide pour votre avatar")
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;


    /**
     *@Assert\EqualTo(propertyPath="hash", message="Votre mot de passe n'est pas le même")
     */
    public $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, minMessage="Votre introduction doit faire au moins 10 caratères")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100, minMessage="Votre description doit faire au moins 100 caractères")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ad", mappedBy="author")
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="author", orphanRemoval=true)
     */
    private $comments;

    /**
     * Le captcha à remplir
     *
     */
    protected $captchaCode;

    /**
     * La case à cocher pour valider le formulaire
     *
     */
    private $validate;

    /**
     * Affiche le nom complet
     *
     * @return void
     */
    public function getFullName()
    {
        return "{$this->firstName} " . strtoupper("{$this->lastName}");
    }

    /**
     * Initialise le slug
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * @return void 
     */
    public function initializeSlug()
    {
        if (empty($this->slug)) {

            $slugify =  new Slugify();
            $this->slug = $slugify->slugify($this->firstName . ' ' . $this->lastName);
        }
    }

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->contains($ad)) {
            $this->ads->removeElement($ad);
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    public function getRoles()
    {
        $roles = $this->userRoles->map(function ($role) {

            return $role->getTitle();
        })->toArray();

        $roles[] = 'ROLE_USER';

        return $roles;
    }

    public function getPassword()
    {
        return $this->hash;
    }

    public function getSalt()
    {
    }

    public function getUsername()
    {
        return $this->email;
    }

    public function eraseCredentials()
    {
    }

    public function getCaptchaCode()
    {
        return $this->captchaCode;
    }

    public function setCaptchaCode($captchaCode)
    {
        $this->captchaCode = $captchaCode;
    }

    public function getvalidate()
    {
        return $this->validate;
    }

    public function setvalidate($validate)
    {
        $this->validate = $validate;
    }


    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use App\Form\ApplicationType;
use App\Form\DataTransformer\FrenchToDateTimeTransformer;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Validator\Constraints\GroupSequence;

class BookingType extends ApplicationType
{

    private $transformer;

    public function __construct(FrenchToDateTimeTransformer $transformer)
    {
        $this->transformer = $transformer;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('startDate', TextType::class, $this->getConfiguration("Date d'arrivée", "La date à laquelle vous contez arriver"))
            ->add('endDate', TextType::class, $this->getConfiguration("Date de départ", "La date à laquelle vous comptez partir"))
            ->add('comment', TextareaType::class, $this->getConfiguration(false, " Si vous avez un commentaire n'hésitez pas à en faire part !", [
                "required" => false
            ]));

        $builder->get('startDate')->addModelTransformer($this->transformer);
        $builder->get('endDate')->addModelTransformer($this->transformer);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
            'validation_groups' => new GroupSequence(['Default', 'front'])
        ]);
    }
}

templates/booking/book.html.twig
{% extends "base.html.twig" %}

{% block title %}Réserver l'annonce:
	{{ ad.title }}
{% endblock %}

{% block stylesheets %}
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha256-siyOpF/pBWUPgIcQi17TLBkjvNgNQArcmwJB8YvkAgg=" crossorigin="anonymous"/>
{% endblock %}

{% block body %}

	<div class="container">
		<h1 class="mt-5">Réserver pour l'annonce: <strong>{{ ad.title }}</strong></h1>

		<p class="mb-5">
			Vous êtes sur le point de réserver le bien de:
			<strong>{{ ad.author.fullName }}</strong>
			Dites nous tout, on s'occupe du reste !
		</p>

		{{ form_start(form) }}
		<div class="alert alert-light">
			<h2 class="h4">Commencez par nous dire quelles sont les dates qui vous intéressent !</h2>

			<div class="row">
				<div class="col" style="color: black;">
					{{ form_row(form.startDate) }}
				</div>
				<div class="col" style="color: black;">
					{{ form_row(form.endDate) }}
				</div>
			</div>
			<h4 class="mt-2">Montant du séjour:
				<span id="amount">... </span>&euro;
			</h4>
			<span id="days">0</span>
			nuit(s) à
			{{ ad.price | number_format(2,',','')}} &euro;
			par nuit
			<h4 class="mt-3">Vous avez un commentaire ?</h4>
			{{ form_row(form.comment) }}
		</div>


		<h2 class="mt-4 text-center">Vous avez terminé ?
		</h2>
		<p class="text-center">Vacances de rêve ? Hébergement pour le boulot ?  Peu importe, on est ensemble !</p>

		<button id="validate" type="submit" class="btn btn-success">Je réserve !</button>
		{{ form_end(form) }}
	</div>

{% endblock %}

{% block javascripts %}
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha256-bqVeqGdJ7h/lYPq6xrPv/YGzMEb6dNxlfiTUHSgRCp8=" crossorigin="anonymous"></script>

	<script>
		$(document).ready(function () {
			$('#booking_startDate, #booking_endDate').datepicker({
			format: 'dd/mm/yyyy',
			datesDisabled: [{% for day in  ad.notAvailableDays %}"{{ day.format('d/m/Y') }}",{% endfor %}],
			startDate: new Date()
		});

		$('#booking_startDate, #booking_endDate').on('change', calculateAmount);
	});

	function calculateAmount()
	{
		// Regex pour le format de date
		// (\d+)\/(\d+)\/(\d{4})

		// Récupération des dates
		const startDate = new Date($('#booking_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/,'$3-$2-$1'));
		const endDate = new Date($('#booking_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/,'$3-$2-$1'));

		if (startDate && endDate && startDate < endDate) {
			// Nombre de milliseconde dans un jour
			const DAY_TIME = 24 * 60 * 60 * 1000;

			const interval = endDate.getTime() - startDate.getTime();
			const days = interval / DAY_TIME;

			const amount = days * {{ ad.price }};

			$('#days').text(days);
			$('#amount').text(amount.toLocaleString('fr-FR') +" ");
		}
	}

	</script>
{% endblock %}

templates/booking/edit.html.twig
{% extends "base.html.twig" %}

{% block title %}Modification de réservation pour l'annonce:
	{{ booking.title }}
{% endblock %}

{% block stylesheets %}
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha256-siyOpF/pBWUPgIcQi17TLBkjvNgNQArcmwJB8YvkAgg=" crossorigin="anonymous"/>
{% endblock %}
{% block body %}
	<div class="container">
		<h1 class="my-5">Modifier la réservation n°{{ booking.id }}</h1>

		{{ form_start(form) }}

		<div class="row">
			<div class="col">
				{{ form_row(form.startDate) }}
				{{ form_row(form.endDate) }}
				{{ form_row(form.comment) }}

				<button type="submit" class="btn btn-success">
					<i class="fas fa-check"></i>
					Enregistrer les modifications
				</button>

			</div>
		</div>
		{{ form(form) }}
		</div>

	{% endblock %}

templates/booking/show.html.twig
{% extends "base.html.twig" %}

{% block title %}Réservation n°{{ booking.id }}
{% endblock %}

{% block body %}

	{% set ad = booking.ad %}
	{% set author = ad.author %}

	<div class="container d-flex flex-column align-items center">
		<div class="d-flex justify-content-between align-items-center">
			<h1 class="my-5">Votre réservation (n°{{ booking.id }})</h1>
			<a title="Télécharger ma réservation" href="{{ path('booking_pdf', { 'id' : booking.id }) }}" class="btn btn-info">
				<i class="fas fa-download"></i>
			</a>
		</div>

		{% if app.request.query.get('success') %}
			<div class="alert alert-success">
				<h4 class="alert-heading">Bravo votre réservation a eu lieu avec succès !</h4>

				<p>
					Votre réservation auprès de
					<strong>
						<a href="{{ path('user_show', {'slug' : author.slug}) }}">{{ author.fullName }}</a>
					</strong>
					pour l'annonce
					<strong>
						<a href="{{ path('ads_show', {'slug' : ad.slug}) }}">{{ ad.title }}</a>
					</strong>
					a bien été prise en compte !
				</p>
				<p>
					Veuillez valider votre panier afin de finaliser votre réservation
				</p>
				{# TODO: Vérifier si la réervation est dans le panier #}
				<a href="{{path('cart_add', {'id' : booking.id}) }}" class="btn btn-success">Ajouter au panier
					<i class="fas fa-shopping-basket"></i>
				</a>
			</div>
		{% endif %}


		<div class="row">
			<div class="col">
				<div class="alert alert-light">
					<h2>Détails</h2>
					<dl class="row">
						<dt class="col-md-4">Numéro</dt>
						<dd class="col-md-8">{{ booking.id }}</dd>
						<dt class="col-md-4">Date d'arrivée</dt>
						<dd class="col-md-8">{{ booking.startDate | date('d/m/Y') }}</dd>
						<dt class="col-md-4">Date de départ</dt>
						<dd class="col-md-8">{{ booking.endDate | date('d/m/Y') }}</dd>
						<dt class="col-md-4">Nombre de nuits</dt>
						<dd class="col-md-8">{{ booking.duration }}</dd>
						<dt class="col-md-4">Montant total</dt>
						<dd class="col-md-8">{{ booking.amount | number_format(2,',','')}}
							&euro;</dd>
						<dt class="col-md-4">Commentaire</dt>
						<dd class="col-md-8">{{ booking.comment | default('Aucun commentaire ..')}}</dd>
					</dl>

					<hr>

					<h2 class="alert-heading">Votre hôte</h2>
					<div class="row mb-3">
						<div class="col-3">
							<img src="{{ author.picture }}" class="avatar avatar-medium" alt="L'avatar de {{ author.fullName }}">
						</div>
						<div class="col">
							<h4>
								<a href="{{ path('user_show', {'slug' : author.slug}) }}">{{ author.fullName }}</a>
							</h4>
							<span class="badge badge-primary">{{ author.ads | length }}
								annonces</span>
						</div>
					</div>

					{{ author.description | raw }}

					<a href="{{ path('user_show', {'slug' : author.slug}) }}" class="btn btn-primary">Plus d'infos sur
						{{ author.firstName }}</a>
				</div>

				<div class="alert alert-light" id="comment">

					<h2 class="alert-heading">Votre avis compte !</h2>
					{# Si la date d'aujourdh'ui est supérieur à la date de départ :: signe à changer '<'   =>   '>' #}
					{% if date() > date(booking.endDate) %}

						{% set comment  = booking.ad.commentFromAuthor(app.user) %}
						{# Si l'utilisateur a déjà commenté l'annonce #}
						{% if comment is not null %}
							<blockquote>
								{{ comment.content }}
							</blockquote>

							<strong>Note:
								{% include "partials/rating.html.twig" with {'rating' : comment.rating} %}</strong>

						{% else %}

							{{ form_start(form) }}
							{{ form_widget(form) }}
							<button type="submit" class="btn btn-success">Envoyer</button>
							{{ form_end(form) }}
						{% endif %}
					{% else %}
						<p>Vous ne pourrez pas noter cette annonce tant que votre voyage ne sera pas complet !</p>
					{% endif %}
				</div>
			</div>

			<div class="col">

				<div class="alert laert-light">
					<h2 class="alert-heading">Votre hébergement</h2>

					<h4>
						<a href="{{ path('ads_show', { 'slug' : ad.slug }) }}">{{ ad.title }}</a>
					</h4>

					<img src="filname" alt="Image de {{ ad.title }}" class="img-fluid">

					<div style="color: black;">
						{{ ad.content | raw }}
					</div>

					<div
						class="d-flex justify-content-between">
						{# <a href="{{ path('ads_show', { 'slug' : ad.slug }) }}" class="btn btn-primary">Plus d'informations</a> #}

						<a href="{{ path('ads_show', { 'slug' : ad.slug }) }}" class="more float-left hvr-icon-pulse-grow">En savoir

							<i class="fas fa-plus-circle hvr-icon"></i>
						</a>

					</div>
					<div class="mt-4 d-flex justify-content-between">
						<a href="{{ path('booking_delete', {'id' : booking.id}) }}" class=" btn btn-danger annuler-reservation">Annuler la réservation</a>
						<a href="#" class="btn btn-success">Valider et payer la réservation</a>
					</div>
				</div>
			</div>
		</div>
	</div>

{% endblock %}