src/Entity/Ad.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdRepository")
 * @Vich\Uploadable()
 * @ORM\HasLifecycleCallbacks()
 *  @UniqueEntity
 * (
 * fields={"title"},
 * message="Une autre annonce a déjà ce titre"
 * )
 */
class Ad
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     *
     * @var string|null
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $filename;

    /**
     * Correspond à l'imagé uploadé
     *
     * @var File|null
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="filename")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, max=255, minMessage="Le titre doit faire au moins 10 caractères !", maxMessage="Le titre doit faire au plus 255 caratères")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=20, minMessage="L'introduction doit faire au moins 20 caractères !")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100, minMessage="La description doit faire au moins 100 caractères !")
     */
    private $content;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="ad", orphanRemoval=true)
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * Initialise le slug
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * @return void 
     */
    public function initializeSlug()
    {
        if (empty($this->slug)) {

            $slugify =  new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }


    /**
     * Permet d'obtenir un tableau des jours qui ne sont pas disponibles pour cette annonce
     *
     * @return array Un tableau d'objets DateTime représentant les jours d'occupation 
     */
    public function getNotAvailableDays()
    {
        $notAvailableDays = [];

        foreach ($this->bookings as $booking) {
            // Calculer les jours qui sont entre la date d'arrivée et de départ
            $resultat = range(
                $booking->getStartDate()->getTimestamp(),
                $booking->getEndDate()->getTimestamp(),
                24 * 60 * 60
            );

            // Transformer $resultat en un tableau de vrai date de type DateTime
            $days = array_map(function ($dayTimestamp) {
                return new \DateTime(date('Y-m-d', $dayTimestamp));
            }, $resultat);

            // Fusion entre le tableau $notAvailableDays et $days
            $notAvailableDays = array_merge($notAvailableDays, $days);
        }

        return $notAvailableDays;
    }

    /**
     * Permet d'afficher la note moyenne de l'annonce
     *
     * @return float
     */
    public function getAvgRating()
    {
        // Calculé la somme des notations 
        $sum = array_reduce($this->comments->toArray(), function ($total, $comment) {
            return $total + $comment->getRating();
        }, 0);

        // Faire la division pour avoir la moyenne 
        if (count($this->comments) > 0) return $sum / count($this->comments);

        return 0;
    }

    /**
     * Permet de récupérer le commentaire d'un auteur par rapport à une annonce
     *
     * @param User $author
     * 
     * @return Comment | null
     */
    public function getCommentFromAuthor(User $author)
    {
        foreach ($this->comments  as $comment) {
            if ($comment->getAuthor() === $author) return $comment;
        }

        return null;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }

    /**
     * Get correspond à l'imagé uploadé
     *
     * @return  File|null
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * Set correspond à l'imagé uploadé
     *
     * @param  File|null  $imageFile  Correspond à l'imagé uploadé
     *
     * @return  self
     */
    public function setImageFile($imageFile)
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile) {
            $this->updatedAt = new \DateTime('now');
        }

        return $this;
    }

    /**
     * Get the value of filename
     *
     * @return  string|null
     */
    public function getFilename()
    {
        return $this->filename;
    }

    /**
     * Set the value of filename
     *
     * @param  string|null  $filename
     *
     * @return  self
     */
    public function setFilename($filename)
    {
        $this->filename = $filename;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

src/Form/AdType.php
<?php

namespace App\Form;

use App\Entity\Ad;
use App\Form\ApplicationType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class AdType extends ApplicationType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, $this->getConfiguration("Titre", "Tapez un super titre pour votre annonce"))
            ->add('slug', TextType::class, $this->getConfiguration("Adresse web", "Tapez l'adresse web (automatique)", [
                'required' => false
            ]))
            ->add('introduction', TextType::class, $this->getConfiguration("Introduction", "Donnez une description grlobal de l'annonce"))
            ->add('content', TextareaType::class, $this->getConfiguration("Description détaillé", "Tapez une description qui donn envie de venir chez vous"))
            ->add('rooms', IntegerType::class, $this->getConfiguration("Nombre de chambres", "Le nombre de chambres disponible"))
            ->add('price', MoneyType::class, $this->getConfiguration("Prix", "Indiquez le prix que vous voulez pour une nuit"))
            ->add('imageFile', FileType::class, $this->getConfiguration("Importer l'image principale", "Choisir un fichier de votre PC", [
                'required' => false
            ]))
            ->add('images', CollectionType::class, [
                'entry_type' => ImageType::class,
                'allow_add' => true,
                'allow_delete' => true
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Ad::class,
        ]);
    }
}

src/Controller/AdController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Form\AdType;
use App\Form\SearchAdType;
use App\Repository\AdRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AdController extends AbstractController
{

    /**
     * @Route("/ads", name="ads_index")
     * 
     * @return Response
     */
    public function index(AdRepository $repo, Request $request)
    {
        $ads = $repo->findAll();



        return $this->render('ad/index.html.twig', [
            'ads' => $ads,
        ]);
    }

    /**
     * Permet de créer une annonce
     *
     * @Route("/ads/new", name="ads_create")
     * @IsGranted("ROLE_USER")
     * 
     * @return Response
     */
    public function create(Request $request, EntityManagerInterface $manager)
    {
        $ad = new Ad();

        $form = $this->createForm(AdType::class, $ad);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            foreach ($ad->getImages() as $image) {

                $image->setAd($ad);
                $manager->persist($image);
            }
            $ad->setAuthor($this->getUser());
            $ad->setUpdatedAt(new \DateTime('now'));
            $ad->initializeSlug();
            $manager->persist($ad);
            $manager->flush();

            $this->addFlash(
                'success',
                "L'annonce <strong> {$ad->getTitle()}</strong> a bien été enregistrer !"
            );

            return $this->redirectToRoute('ads_show', [
                'slug' => $ad->getSlug()
            ]);
        }

        return $this->render('ad/new.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * Permet de modifier une annonce
     *
     * @Route("/ads/{slug}/edit", name="ads_edit")
     * @Security("is_granted('ROLE_USER') and user === ad.getAuthor()",  message="Cette annonce ne vous appartient pas, vous ne pouvez pas la modifier")
     * 
     * @return Response
     */
    public function edit(Ad $ad, Request $request, EntityManagerInterface $manager)
    {
        $form = $this->createForm(AdType::class, $ad);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            foreach ($ad->getImages() as $image) {

                $image->setAd($ad);
                $manager->persist($image);
            }
            $ad->initializeSlug();
            $manager->persist($ad);
            $manager->flush();

            $this->addFlash(
                'success',
                "L'annonce <strong> {$ad->getTitle()}</strong> a bien été modifié !"
            );

            return $this->redirectToRoute('ads_show', [
                'slug' => $ad->getSlug()
            ]);
        }

        return $this->render('ad/edit.html.twig', [
            'form' => $form->createView(),
            'ad' => $ad
        ]);
    }

    /**
     * Permet d'afficher une seule annonces
     *
     * @Route("/ads/{slug}", name="ads_show")
     * 
     * @return Response
     */
    public function show(Ad $ad)
    {
        return $this->render('ad/show.html.twig', [
            'ad' => $ad
        ]);
    }

    /**
     * Permet de supprimer une annonce
     * 
     * @Route("/ads/{slug}/delete", name="ads_delete")
     * @Security("is_granted('ROLE_USER') and user == ad.getAuthor()", message="Vous n'avez pas le droit d'accéder à cette ressource")
     *
     * @param Ad $ad
     * @param EntityManagerInterface $manager
     * @return Response
     */
    public function delete(Ad $ad, EntityManagerInterface $manager)
    {

        if (count($ad->getBookings()) > 0 || count($ad->getComments()) > 0) {
            $this->addFlash(
                'warning',
                "Vous ne pouvez pas supprimer l'annonce <strong>{$ad->getTitle()}</strong> car elle possède déjà des réservations ou des commentaires veuillez contacter l'admin pour plus d'infos !"
            );
        } else {
            $manager->remove($ad);
            $manager->flush();

            $this->addFlash(
                'success',
                "L'annonce <strong>{$ad->getTitle()}</strong> a bien été supprimé"
            );
        }

        return $this->redirectToRoute("ads_index");
    }

    /**
     * Permet d'afficher la page de recherche
     * 
     * @Route("/search/ads", name="ads_search")
     *
     * @return Response
     */
    public function search(Request $request, AdRepository $adRepository)
    {

        $ads = [];
        $searchAdForm = $this->createForm(SearchAdType::class);
        $searchAdForm->handleRequest($request);

        if ($searchAdForm->isSubmitted() && $searchAdForm->isValid()) {
            $criteria = $searchAdForm->getData();
            $ads = $adRepository->search($criteria);
        }

        return $this->render('ad/search.html.twig', [
            'search_form' => $searchAdForm->createView(),
            'ads' => $ads
        ]);
    }
}

templates/ad/_ad.html.twig
{% set url = path('ads_show', {'slug' : ad.slug}) %}
<div class="col-md-4 target my-3">
	<div class="card bg-light mb-3">
		<div class="card-header">
			<strong>{{ ad.city }}</strong><br>
			{{ ad.rooms }}
			chambres,
			<strong>{{ ad.price  | number_format(2,',','')}}
				&euro; / nuit</strong><br>
			{% if ad.comments | length > 0 %}
				{% include "partials/rating.html.twig" with {'rating' : ad.avgRating} %}
			{% else %}
				<small>Pas encore noté</small>
			{% endif %}
		</div>
		<a href="{{ url }}">
			<img src="{{ vich_uploader_asset(ad, 'imageFile') }}" alt="Image de l'annonce {{ ad.slug }}" style="height: 200px; width: 100%; display: block;">


		</a>
		<div class="card-body">
			<h4 class="card-title">
				{{ ad.title }}
			</h4>
			<p class="card-text mt-3 mb-4">
				{{ ad.introduction }}
			</p>
			<div class="test d-flex justify-content-between align-items-center">
				<a href="{{ url }}" class="more float-left hvr-icon-pulse-grow">En savoir
					<i class="fas fa-plus-circle hvr-icon"></i>
				</a>

				{% if app.user and app.user != ad.author  %}

					<a href="{{ path('booking_create', {'slug' : ad.slug, 'id': ad.id}) }}" class="reserver hvr-icon-buzz">Je réserve 
					<i class="hvr-icon fas fa-exclamation-circle"></i></a>

				{% endif %}
				{% if  app.user and app.user == ad.author %}

					<a href="{{ path('ads_edit', {'slug' : ad.slug }) }}" class="modifier hvr-icon-spin float-right">Modifier l'annonce
					<i class="hvr-icon fas fa-cog"></i>
					</a>

					{% else %}

				{% endif %}
			</div>
		</div>
	</div>
</div>

<script>
	document.addEventListener("DOMContentLoaded", function () { // animation d'apparition sur les card des annonces
ScrollReveal().reveal('.target', {delay: 250});
});
</script>

templates/ad/_collection.html.twig
{% block _ad_images_entry_row %}

	{{ form_widget(form) }}
{% endblock %}

{% block _ad_images_widget %}
	<p>Ici, vous pouvez ajouter d'autres images à l'annonce !</p>

	{{ form_widget(form) }}

	<input type="hidden" id="widgets-counter" value="0">

	<div class="form-group">
		<button type="button" id="add-images" class="btn btn-primary">
			<i class="fas fa-plus"></i> 
			Ajouter une image
		</button>
	</div>
{% endblock %}

{% block _ad_images_entry_widget %}

	<div class="form-group" id="block_{{ id }}">
		<div class="row">
			<div class="col-10">
				<div class="row">
					<div class="col">
						{{ form_widget(form.url) }}
					</div>
					<div class="col">
						{{ form_widget(form.caption) }}
					</div>
				</div>
			</div>
			<div class="col-2">
				<button type="button" data-action="delete" data-target="#block_{{ id }}" class="btn btn-danger">X</button>
			</div>
		</div>
	</div>
{% endblock %}

templates/ad/edit.html.twig
{% extends "base.html.twig" %}

{% block title %}Modification d'une annonce
{% endblock %}

{% form_theme form "ad/_collection.html.twig" %}
{% block body %}

	<div class="container">
		<h1 class="my-5">Modifier l'annonce:
			{{ ad.title }}</h1>

		{{ form_start(form) }}

		{{ form_widget(form) }}

		<button type="submit" class="btn btn-primary">Enregistrer</button>

		{{ form_end(form) }}
	</div>
{% endblock %}


{% block javascripts %}

	{{ encore_entry_script_tags('js/ad') }}
{% endblock %}

templates/ad/form_collections.html.twig
{% extends "base.html.twig" %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}

{% form_theme form _self %}

{% block _ad_images_entry_row %}

	{{ form_widget(form) }}
{% endblock %}

{% block _ad_images_widget %}
	<p>Ici, vous pouvez ajouter d'autres images à l'annonce !</p>

	{{ form_widget(form) }}

	<input type="hidden" id="widgets-counter" value="0">

	<div class="form-group">
		<button type="button" id="add-images" class="btn btn-primary">Ajouter une image</button>
	</div>
{% endblock %}

{% block _ad_images_entry_widget %}

	<div class="form-group" id="block_{{ id }}">
		<div class="row">
			<div class="col-10">
				<div class="row">
					<div class="col">
						{{ form_widget(form.url) }}
					</div>
					<div class="col">
						{{ form_widget(form.caption) }}
					</div>
				</div>
			</div>
			<div class="col-2">
				<button type="button" data-action="delete" data-target="#block_{{ id }}" class="btn btn-danger">X</button>
			</div>
		</div>
	</div>
{% endblock %}

{% block javascripts %}
	<script>
		$('#add-images').click(function () { // Je récupère le numéro des futurs champs que je vais créer
const index = +$('#widgets-counter').val();

// Je récupère le prototy des entrées
const tmpl = $('#ad_images').data('prototype').replace(/__name/g, index);

// J'injecte ce code au sein de la div
$('#ad_images').append(tmpl);

$('#widgets-counter').val(index+1);

// Je gère le button supprimer
handleDeleteButtons();
});

function handleDeleteButtons() {
$('button[data-action="delete"]').click(function () {
const target = this.dataset.target;
$(target).remove();

});
}

handleDeleteButtons();
	</script>
{% endblock %}

templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos magnifiques annonces
{% endblock %}

{% block body %}

	<div class="container">

		<h1 class="h1">Voici les annonces des hôtes</h1>

		<div class="row">
			<span class="mb-3">
				<a href="{{path('ads_search')}}" class="plus-recherche hvr-icon-wobble-horizontal">Recherche avancée <i class="fas fa-search-plus hvr-icon"></i></a>
			</span>
		</div>


		<div class="row">
			{% for ad in ads %}
				{% include "ad/_ad.html.twig" %}
			{% endfor %}
		</div>
	</div>


{% endblock %}

templates/ad/search.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Rechercher une annonce
{% endblock %}

{% block body %}
	<div class="container">
		<div class="row d-flex justify-content-center">
			<div class="col-10 col-md-6">
				<h1 class="my-5 text-center">Effectuer une recherche</h1>

				{{ form(search_form) }}

				</div>
			</div>
			{% if app.request.method == 'POST' %}
				<div class="row">
					<div class="col-10 offset-1">
						{% if ads | length == 0 %}
							<h2 class="my-5 text-center">Aucun résultat pour votre recherche</h2>
						{% else %}
							<h2 class="my-5 text-center">Résultats de la recherche</h2>
						<div class="row">
								{% for ad in ads %}
									{% include "ad/_ad.html.twig" %}
								{% endfor %}
							{% endif %}
						</div>
					</div>
				</div>
			{% endif %}
		</div>

	{% endblock %}

templates/ad/show.html.twig
{% extends "base.html.twig" %}

{% block title %}
	{{ ad.title }}
{% endblock %}

{% block body %}

	<div class="new-title" style="background-image: url({{ vich_uploader_asset(ad, 'imageFile') }});">

		<div class="container">
			<h1>{{ ad.title }}</h1>
			<p>{{ ad.introduction }}</p>

			<p class="h2">
				<strong>{{ ad.rooms }}
					chambre(s)</strong>
				pour
				<strong>{{ad.price | number_format(2,',','')}}
					&euro; / nuit</strong>
			</p>
			<a href="{{ path('booking_create', {'slug' : ad.slug, 'id': ad.id}) }}" class="btn btn-primary">Réserver </a>

			{% if app.user and app.user == ad.author %}

				<a href="{{ path('ads_edit', {'slug' : ad.slug }) }}" class="btn btn-secondary ml-4 mr-4">Modifier l'annonce</a>
				<a href="{{ path('ads_delete', {'slug' : ad.slug}) }}" onclick="return confirm(`Êtes vous sur de vouloir supprimer l'annonce: {{ ad.title }} ?`)" class="btn btn-danger">Supprimer l'annonce</a>
			{% endif %}
		</div>
	</div>

	<div class="container">
		<div class="row">
			<div class="col-md-8 mb-3">
				<h2 class="my-5 my-md-3">Description :</h2>

				{{ ad.content | raw }}

				<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
					<ol class="carousel-indicators">
						{% for image in ad.images %}
							<li data-target="#carouselExampleIndicators" data-slide-to="{{ loop.index0 }}" {% if loop.first %} class="active {% endif %}"></li>
						{% endfor %}
					</ol>
					<div class="carousel-inner">

						{% for image in ad.images %}
							<div class="carousel-item {% if loop.first %} active {% endif %}">
								<img src="{{ image.url }}" class="d-block w-100" alt="...">
								<div class="carousel-caption d-none d-md-block">
									<h5>{{ ad.title }}</h5>
									<p>{{ image.caption }}</p>
								</div>
							</div>
						{% endfor %}
					</div>
					<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
						<span class="carousel-control-prev-icon" aria-hidden="true"></span>
						<span class="sr-only">Previous</span>
					</a>
					<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
						<span class="carousel-control-next-icon" aria-hidden="true"></span>
						<span class="sr-only">Next</span>
					</a>
				</div>

				<hr>

				{% if ad.comments | length > 0  %}
					<h2 class="my-5 mt-md-3">Commentaires de nos voyageurs:</h2>

					<div class="alert alert-info">
						<h4 class="amert-heading text-center ">
							<div class="row align-items-center">
								<div class="col-12" style="color: black;">
									Note globale donnée par nos voyageurs
								</div>
								<div class="col-12 mt-3">
									{% include "partials/rating.html.twig" with{'rating' : ad.avgRating} %}
									<br>
									<small>
										(Calculé sur
										{{ ad.comments | length }}
										avis !)
									</small>
								</div>
							</div>
						</h4>
					</div>

					{% for comment in ad.comments %}
						<div class="rounded mb-3 py-3 px-3" style=" background-color: rgba(21,140,186, 0.05)">
							<strong>{{ comment.author.firstName }}
								<small>
									le
									{{ comment.createdAt | date('d/m/Y') }}
									à
									{{ comment.createdAt | date('H:i') }}
								</small>:
							</strong>

							<blockquote>
								{{ comment.content }}
							</blockquote>

							<strong>Note données:</strong>
							{% include "partials/rating.html.twig" with {'rating' : comment.rating} %}
						</div>
					{% endfor %}
				{% else %}
					<h2>Cette annonce n'a pas encore reçu de commentaires</h2>
				{% endif %}

			</div>
			<div class="col">

				{% set author = ad.author %}
				<div class="row">
					<div class="col-3">
						<a href="{{ path('user_show', {'slug' : author.slug}) }}">
							<img src="{{ author.picture }}" class="avatar avatar-medium" alt="avatar de {{ author.fullName }}">
						</a>
					</div>
					<div class="col">
						<a href="{{ path('user_show', {'slug' : author.slug}) }}">
							<h3>{{ author.fullName }}</h3>
						</a>
						<span class="badge badge-primary">{{ author.ads | length }}
							annonces</span>
						<p>{{ author.description | raw }}</p>
					</div>
				</div>

			</div>
		</div>
	</div>

{% endblock %}